### ISSUE TITLE
ubuntu20.04出现了无法执行的情况

### ISSUE THREAD

**Issue by ghostry** [WencoChen/MineEarth#15]
```
$ /opt/EarthWallpaper
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4e5c8a]

goroutine 1 [running]:
github.com/nfnt/resize.Resize(0x37a, 0x37a, 0x0, 0x0, 0x5, 0x77b6a0, 0x0)
	/home/wenco/go/pkg/mod/github.com/nfnt/resize@v0.0.0-20180221191011-83c6a9932646/resize.go:83 +0x3a
main.(*Wallpaper).draw(0xc000096cc0, 0x0, 0x0, 0x6, 0x0)
	/mnt/e/go/src/earth/wallpaper.go:104 +0x24b
main.(*Wallpaper).Exec(0xc000096cc0)
	/mnt/e/go/src/earth/wallpaper.go:47 +0xf6
main.main()
	/mnt/e/go/src/earth/main.go:23 +0x30
$ uname -ra
Linux momo-hp 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by wksama** [comment]
不好意思，才看到，是原网站换了协议导致的，已经修复
